### PR TITLE
goneovim-nightly: Fix version

### PR DESCRIPTION
**Pull request by shiena**
The current version is not in ascending order so `scoop update` will not detect the update. Therefore, replace it with the update date.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shiena** [comment]
Here's why the checkver failed:
https://github.com/ScoopInstaller/Scoop/issues/5129

**Comment by tech189** [comment]
Nice find, shall we wait for a fix in Scoop or should we make a temporary regex that will match `M/d/yyyy h:m:s tt` (assuming all GitHub actions runners use en-US locale)? @issaclin32

**Comment by issaclin32** [comment]
@tech189 I think we should make a temporary regex fix first, so that we can fix it as sooner.

**Comment by shiena** [comment]
I think a temporary regex is a good idea. However, in the `M/d/yyyy h:m:s` format, I don't know a good way to zero-fill the single-digit month and day and extract the two-digit month and day as they are.
For example, `9/4/2020` converts to `20200904` and `11/23/2020` converts to `20201123`.

**Comment by tech189** [comment]
As a workaround for having to make a regex for the en-US datetime, I just moved the `updated_at` selection from jsonpath into the regex, should work now.

**Comment by shiena** [comment]
@tech189 Great and thank you. This method was a blind spot.

**Review by tech189 — APPROVED** [review]

**Pull request merged**
