### PR TITLE
Added "." to "env_add_path" for all python version

### PR DESCRIPTION
**Pull request by Haffi921**
# Description

Added "." to "env_add_path" of all python version's pythonXX*.json files, like so:
```json
"env_add_path": [
    "scripts",
    "."
]
```
Originally it was simply this: `"env_add_path": "scripts"`.

Changes:
1) This changes the paths that are added to the Environment variable `PATH` when pythonXX is installed
2) These paths are moved to the front of the `PATH` when users run the command `scoop reset pythonXX`

**This is also in line with how scoop's main bucket python is configured.**

## Reasoning
Change 2) is really important and is the reason why I am submitting this change. When you have both scoop's main bucket python installed AND other versions of python from this bucket installed, you will have an issues when you change python versions using `scoop reset pythonXX`

#### Current behaviour
```powershell
PS > scoop reset python
...
PS > python -V
Python 3.10.0

PS > scoop reset python38
...
PS > python -V
Python 3.10.0
```

#### Expected
```powershell
PS > scoop reset python
...
PS > python -V
Python 3.10.0

PS > scoop reset python38
...
PS > python -V
Python 3.8.10
```

## Explanation of this behaviour
When you install main's python or versions' pythonXX, scoop creates shims to python's executables in `~\scoop\shims` which is by default added to the path. However with main's python, it also adds to the path `~\scoop\apps\python\current` (Corresponds to the path "." added to the `.json` file in this fix) which contains direct links to main's python executables, and this path is placed before scoop's `~\scoop\shims` path at install. Effectively, the executables in this path shadow the ones in `~\scoop\shims`.

Whenever you run `scoop reset python`, scoop moves this path to the top; and more generally the paths specified in this `env_add_path` option. Any attempt at manually moving the scoop  `~\scoop\shims` path to the top is immediately reverted the next time the user runs `scoop reset python`.

These changes will make it so that when you run `scoop reset pythonXX`, its `~\scoop\apps\pythonXX\current` file is moved to the top of the path. When the user runs `scoop reset` for another version or main's python, **that** folder will be moved to the top, and so on...

**As aside**: Additionally, it adds `~\scoop\apps\python[XX]\current\Scripts` which contains `pip`. This works the same way as explained above. However, this folder is already of `env_add_path` so it is not an issue.

## Alternative change
Scoop's main bucket python could be changed to remove "." from its `env_add_path`. Scoop already makes shims for all the executables and additionally switches then whenever you run `scoop reset`. This would have the same effect, just that none of the `~\scoop\apps\python[XX]\current` folders will be added to the path

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

See also #231 which attempts the same issue but only with python27. Additionally, it switches the order of "Scripts" and "." which might (not sure) result in a non-issue asymmetry between main and versions

# How Has This Been Tested?

- [x] My changes have been tested with changing my own installed scoop version bucket `.json` files, and this change works as expected

# Checklist:

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi @Haffi921, please:
- resolve conflicts
- mirror this change for the remaining 5 python manifests
- remove `python.exe` and `pythonw.exe` from the bin field - because we're already adding `.` to PATH. See https://github.com/ScoopInstaller/Main/pull/2144#issuecomment-916831083 for more details.

Thanks!

**Comment by Haffi921** [comment]
Thanks for taking a look. Will do! I am looking at `python27-beta.json` and it has already my proposed change and no persist field, so I assume I should not take the `python.exe` and `pythonw.exe` files out of bin in that one.

Also, for consistency, I am changing the name for 'script' to 'Script' since that is how appears in the newest changes in the main repository. Just to have all the python files the same, I changed it for `python27-beta.json` and `python27.json` although I don't know three things: 1) Are the folders case-insensitive, so that this capitalisation is only about consistency; 2) If it's not case-insensitive, does this change make sense for python 2.7; 3) Is this a change you guys want?

**Comment by Haffi921** [comment]
Ahh the same goes with `python27.json`; it does not have a `persist` field so I am not removing the two file names from `bin`. Let me know if we should perhaps just add a `persist` field for them as well

**Comment by Haffi921** [comment]
I've made all the changes you requested, let me know if there are any other things you want me to change.

**Comment by rashil2000** [comment]
- The removal of `python.exe` and `pythonw.exe` has nothing to do with persist, it has to do with env_add_path. So, for python27-beta.json and python27.json also, you should remove these 2 bins.
- Finally, you missed out python-alpha.json and python-rc.json. All changes need to be done in these 2 manifests too.

**Comment by Haffi921** [comment]
Ahh okay sure!

**Comment by Haffi921** [comment]
All 12 manifests have now been changed and every change is the same:

1. `env_add_path` changed to array with `Scripts` and `.`
2. `python.exe` and `pythonw.exe` removed from `bin` since it is unnecessary with `.` in `env_add_path`.

Let me know if there are any other changes you want :)

**Comment by rashil2000** [comment]
Great, thanks for patiently sitting through with this :)

Just waiting for the AppVeyor CI's green light...

**Comment by Haffi921** [comment]
Sure enough, thanks for reviewing this :)

**Comment by rashil2000** [comment]
AppVeyor is acting weird again, we'll see what happens 🙃

**Comment by Haffi921** [comment]
Yeah weird. But thanks for merging it! I'm really happy this change has been made :)

**Pull request merged**
