### PR TITLE
ffmpeg-shared-4.4.1: Add version 4.4.1

### PR DESCRIPTION
**Pull request by tech189**
A shared version for glslviewer which only works with this version of ffmpeg.

Relates to https://github.com/ScoopInstaller/Main/issues/4634

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Not sure why this hash check is failing!
image

**Comment by kazzarin** [comment]
Manifest filename should end with `.json`

**Pull request merged**
