### PR TITLE
cuda11.0: Add version 11.0.3_451.82

### PR DESCRIPTION
**Pull request by issaclin32**
This adds **CUDA 11.0** to the bucket.

* I named the package as `cuda11.0` according to #341.

* The install script is taken from [main/cuda](https://github.com/ScoopInstaller/Main/blob/master/bucket/cuda.json)

### CODE REVIEW

**Comment by niheaven** [comment]
Add `.json` 🤣 and, if there is no autoupdate, please use sha256 that calculated locally.

**Comment by issaclin32** [comment]
> Add `.json` 🤣 and, if there is no autoupdate, please use sha256 that calculated locally.

Sorry. I immidiately noticed that after I see the PR check failure.

**Comment by niheaven** [comment]
INFO: Hashes

Log of Output:

    Downloading http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_451.48_win10.exe#/dl.7z (2.6 GB)... 
    cuda11.0:  
    Mismatch found  
    	URL:		http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_451.48_win10.exe#/dl.7z 
    	First bytes:	4D 5A 60 00 01 00 00 00 
    	Expected:	5df6f6337427e09466bcaa7bc9c9460d6d03bc04fa59796132fb9a8e8ff82d3f 
    	Actual:		eb1506723f78fd9523f23bcbe88f91474c09eff6bc8bdc2c74e37ac05bfc9624

INFO: Hashes done

**Review by niheaven — APPROVED** [review]

**Pull request merged**
