### PR TITLE
v2rayn-pre: Add Version 6.6

### PR DESCRIPTION
**Pull request by b4imetu**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

See https://github.com/2dust/v2rayN/releases/tag/6.0

### CODE REVIEW

**Comment by b4imetu** [comment]
Still in process…
Please help me refine the powershell script for the `bin` and `guiConfigs` folders.
…maybe the `regex`, too

**Comment by b4imetu** [comment]
Still in process… I'm not sure about the scripts…
Please help me refine the `powershell` script for the bin and `guiConfigs` folders.
See [6.0 Changelog](https://github.com/2dust/v2rayN/releases/tag/6.0)

**Comment by b4imetu** [comment]
Please help me refine the scripts for the `bin` and `guiConfigs` folders 
The file directory of the `6.x` version is different from the old `5.x` version
See [6.0 Changelog](https://github.com/2dust/v2rayN/releases/tag/6.0)

**Comment by b4imetu** [comment]
/verify
Updated file directory, please review https://github.com/ScoopInstaller/Versions/pull/907/commits/799e3a313e53bdcc6e0eb329b1832697bd017944

**Comment by rasa** [comment]
```batch
--> Running: scoop install  v2rayn-pre.json

Installing 'xray' (1.7.2) [64bit] from main bucket
Xray-windows-64.zip (20.4 MB) [===============================================================================================================================================================================] 100%
Checking hash of Xray-windows-64.zip ... ok.
Extracting Xray-windows-64.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\xray\current => ~\scoop\apps\xray\1.7.2
Creating shim for 'xray'.
Persisting config.json
'xray' (1.7.2) was installed successfully!
Installing 'v2rayn-pre' (6.6) [64bit]
v2rayN.7z (11.4 MB) [=========================================================================================================================================================================================] 100%
Checking hash of v2rayN.7z ... ok.
Extracting v2rayN.7z ... done.
Running pre_install script...
Creating hardlink for wxray.exe
Creating hardlink for xray.exe
Creating hardlink for geoip.dat
Creating hardlink for geosite.dat
Linking ~\scoop\apps\v2rayn-pre\current => ~\scoop\apps\v2rayn-pre\6.6
Creating shim for 'v2rayN'.
Creating shortcut for v2rayN (v2rayN.exe)
Persisting guiConfigs
'v2rayn-pre' (6.6) was installed successfully!
'v2rayn-pre' suggests installing 'extras/windowsdesktop-runtime-lts'.
'v2rayn-pre' suggests installing 'main/v2ray'.

--> Refreshing environment variables

--> Comparing ARP entries

PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop list
Installed apps:

Name       Version          Source                                                          Updated             Info
----       -------          ------                                                          -------             ----
7zip       22.01            main                                                            2023-01-25 12:26:36
dark       3.11.2           main                                                            2023-01-25 12:26:53
git        2.39.1.windows.1 main                                                            2023-01-25 12:26:52
innounp    0.50             main                                                            2023-01-25 12:26:52
lessmsi    1.10.0           main                                                            2023-01-25 12:26:54
v2rayn-pre 6.6              C:\Users\WDAGUtilityAccount\Desktop\SandboxTest\v2rayn-pre.json 2023-01-25 12:27:01
xray       1.7.2            main                                                            2023-01-25 12:26:58


PS C:\Users\WDAGUtilityAccount\Desktop\bucket> scoop uninstall v2rayn-pre
Uninstalling 'v2rayn-pre' (6.6).
Running uninstaller script...
Removing shim 'v2rayN.shim'.
Removing shim 'v2rayN.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\v2rayN.lnk
Unlinking ~\scoop\apps\v2rayn-pre\current
'v2rayn-pre' was uninstalled.
PS C:\Users\WDAGUtilityAccount\Desktop\bucket>
```

**Pull request merged**
