### PR TITLE
Python 3.70b1 added!

### PR DESCRIPTION
**Pull request by yigitemres**
Python 3.70b1 is added.
Installation is working but not sure for autoupdating. Any correction are welcomed!

### CODE REVIEW

**Comment by rasa** [comment]
Since we have packages named [python27](https://github.com/scoopinstaller/versions/blob/master/python27.json) and python3 ([python](https://github.com/lukesampson/scoop/blob/master/bucket/python.json)), I think this package should be named simply python-beta, as a beta of the python27 package would be named python27-beta. Agreed? There will never multiple 3.x betas.

**Comment by rasa** [comment]
Also, the checkver needs to be changed to something like (untested):
````
"checkver": {
  "url": "https://www.python.org/downloads/windows/",
  "re": "/downloads/release/python-3[^\"]*\">Python\s*([\\da-z.]+)"
}
````

**Comment by yigitemres** [comment]
@rasa thx for your comments and contributions for this project. this is my first time adding software to buckets. i simply copy paste python file and change accordingly to beta. i will change name immediately. i don't want to change chekver part until new version of beta is coming.

**Comment by rasa** [comment]
You either need to add the checkver (preferred) or remove the autoupdate, because the two work together, and you have the wrong checkver for the 3.7 beta branch

**Comment by yigitemres** [comment]
@rasa as i said this is my first time creating app manifest. (actually im not even created it im just edited it.) if i have chance (you guys are really fast) to add other apps to repo, i will be more carefull. thx for your warnings.
@r15ch13 thx for cleaning my mess... 🥂

**Pull request merged**
