### PR TITLE
fix: godot url #955

### PR DESCRIPTION
**Pull request by acesyde**
Fix Godot autoupdate url

Relates to #955

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by acesyde** [comment]
something to do @rasa ?

**Comment by deevus** [comment]
I've updated the other manifests to match (godot-rc, godot-mono-rc).

I think what the issue is with the failing updates is that they aren't on the first page anymore.

**Pull request merged**
