### PR TITLE
rambox-ce: Add version 0.7.9

### PR DESCRIPTION
**Pull request by niheaven**
Relates to https://github.com/ScoopInstaller/Extras/pull/7780

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
From https://github.com/ScoopInstaller/Extras/pull/7780#issuecomment-1017577654

> We will release one more CE version which users can migrate

If you remove checkver, how will this get updated

**Comment by niheaven** [comment]
Oh, I ignore the sentence... I'll add it again.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
