### PR TITLE
postgresql: Add version 15.5

### PR DESCRIPTION
**Pull request by rdbisme**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rdbisme** [comment]
@CaselIT for review. 

PS: I think all the binaries should be added in the `PATH` (i.e. `pg_ctl`, etc...)

**Review by CaselIT — APPROVED** [review]
Lgtm

**Review by simonmcconnell — APPROVED** [review]

**Comment by rdbisme** [comment]
@HUMORCE

**Review by HUMORCE — APPROVED** [review]

**Comment by rdbisme** [comment]
Can we merge it @HUMORCE?

**Pull request merged**
