### PR TITLE
postgresql11: add version 11.14

### PR DESCRIPTION
**Pull request by CaselIT**
hi,

I've added a file for postgresql 11.
The file is taken from https://github.com/ScoopInstaller/Main/blob/master/bucket/postgresql.json but adapted to use version 11

### CODE REVIEW

**Comment by rashil2000** [comment]
You should remove checkver and autoupdate, otherwise the manifest will get updated to version 14

**Comment by CaselIT** [comment]
Of course, thanks!

Since I'm here could I also add v12 and v13, or do you prefer separate pr?

**Comment by rashil2000** [comment]
Separate PR - helps us keep track of stuff better

**Comment by CaselIT** [comment]
I've updated. I've also noticed that since I've created the file (a couple of weeks ago) version 11.14 was released. I've also changed to that

**Review by rashil2000 — APPROVED** [review]

**Comment by CaselIT** [comment]
btw looking at the current pg10 
https://github.com/ScoopInstaller/Versions/blob/345c30f8c9f6f0330efa27c7f572e0ed114a6b81/bucket/postgresql10.json#L29-L42

there seems a way of enabling the auto update. I can try adding it also for this one

**Comment by CaselIT** [comment]
I've added the auto update that should look only for v11.x

**Comment by CaselIT** [comment]
The issue with the checker seems to be
`URL https://www.postgresql.org/ftp/source/ is not valid` 

Not sure that's the issue here. https://www.postgresql.org/ftp/source/ works with the browser or curl

**Comment by rashil2000** [comment]
Yeah, it works for me too. Not sure what's going on with GitHub Action's user agent. @issaclin32 pointers?

**Comment by CaselIT** [comment]
seems to be a ssl certificate ussue. the complete error is 
```
     postgresql11:  
    The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure. 
    URL https://www.postgresql.org/ftp/source/ is not valid
```

maybe the certificate on that site id too new or unsupported by the checker script?

**Comment by CaselIT** [comment]
The site seems to use Let's Encrypt, maybe it's related to this? https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

the http version just returns 301 so that's not usable

**Comment by rashil2000** [comment]
I think we can merge this for now. Manual verification works here.

**Comment by issaclin32** [comment]
Still not sure where the error comes from?
The validator should be executing these parts:
https://github.com/Ash258/Scoop-GithubActions/blob/main/src/Action/PR.psm1#L191
https://github.com/ScoopInstaller/Scoop/blob/master/bin/checkver.ps1#L103
https://github.com/ScoopInstaller/Scoop/blob/59088a9f0094ecaa0c36793eef232b3af237a59b/lib/core.ps1#L18

However when I try `curl.exe -v -A "Scoop/1.0" "https://www.postgresql.org/ftp/source/"` it works without a problem.
```
> curl.exe -v -A "Scoop/1.0" "https://www.postgresql.org/ftp/source/"
*   Trying 72.32.157.230...
* TCP_NODELAY set
* Connected to www.postgresql.org (72.32.157.230) port 443 (#0)
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 189 bytes...
* schannel: sent initial handshake data: sent 189 bytes
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 3994
* schannel: encrypted data buffer: offset 3994 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 2/3)
* schannel: encrypted data got 1023
* schannel: encrypted data buffer: offset 5017 length 5018
* schannel: sending next handshake data: sending 158 bytes...
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 5018
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with www.postgresql.org port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /ftp/source/ HTTP/1.1
> Host: www.postgresql.org
> User-Agent: Scoop/1.0
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 13800
* schannel: encrypted data buffer: offset 13800 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 13800 length 103424
* schannel: encrypted data got 27600
* schannel: encrypted data buffer: offset 41400 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 24987
* schannel: encrypted data cached: offset 24987 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 8574
* schannel: encrypted data cached: offset 8574 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 25 Nov 2021 05:20:13 GMT
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: DENY
< Content-Security-Policy: default-src 'self' ; img-src * data: ; script-src 'unsafe-eval' 'self' www.google-analytics.com ssl.google-analytics.com www.googletagmanager.com tagmanager.google.com data: ; connect-src 'self' www.google-analytics.com ssl.google-analytics.com ; media-src 'self' ; style-src 'self' fonts.googleapis.com tagmanager.google.com ; font-src 'self' fonts.gstatic.com data: ; frame-ancestors 'none' ; report-uri https://csp-report.postgresql.org/
< X-XSS-Protection: 1; mode=block
< Vary: Accept-Encoding
< X-Varnish: 2719857 2835482
< Age: 10775
< Via: 1.1 varnish (Varnish/6.0)
< Strict-Transport-Security: max-age=31536000
< Accept-Ranges: bytes
< Transfer-Encoding: chunked
< Connection: keep-alive
<
```

**Comment by issaclin32** [comment]
> I think we can merge this for now. Manual verification works here.

I agree.

**Comment by CaselIT** [comment]
maybe the issue is an old curl version? IIRC the letsencrypt update required some updates because the root certificate they use is quite new?

**Comment by issaclin32** [comment]
> maybe the issue is an old curl version? IIRC the letsencrypt update required some updates because the root certificate they use is quite new?

@rashil2000 We probably need to re-deploy the Docker file of `Scoop-GithubActions`. I am not familiar with Docker, but I can try it on another fork when I have time.

**Comment by rashil2000** [comment]
Maybe we can utilize the https://github.com/ScoopInstaller/Scoop-GithubActions repo we forked?

**Comment by CaselIT** [comment]
I've create the PRs for version 12 and 13. Maybe we can use them to test if updating curl fixes the issue?

**Pull request merged**
