### PR TITLE
python: Use installer script

### PR DESCRIPTION
**Pull request by niheaven**
Use installer script as `main/python` so there will not be ugly item in `Uninstall Programs`.

### CODE REVIEW

**Comment by rashil2000** [comment]
python-alpha link is 404

**Comment by niheaven** [comment]
It's okay on my PC, which link do you mean?

image

I force-update all python* manifests and they are both well here.

**Comment by rashil2000** [comment]
This one:

image

**Comment by niheaven** [comment]
Its download link doesn't contain `a3`, I'll fix them, thanks.

**Comment by niheaven** [comment]
Done.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
