### PR TITLE
added freecad-pre

### PR DESCRIPTION
**Pull request by pandaero**
adding freecad prerelease to bucket

### CODE REVIEW

**Comment by pandaero** [comment]
please help regarding installation procedure in .json

**Comment by pandaero** [comment]
needless to say, I'm having trouble with this 😛 ...

**Comment by pandaero** [comment]
my draft regex: https://regex101.com/r/y1Fv71/1/

**Comment by pandaero** [comment]
removed the checkver, autoupdate, and architecture fields, now simply downloads zip, checks hash, extracts, and makes shortcut

**Comment by tech189** [comment]
I've updated the package with the latest weekly and an autoupdate section, would you like to submit it @pandaero?

```json
{
    "version": "26761",
    "description": "A free and open-source multi-platform parametric 3D modeler.",
    "homepage": "https://www.freecadweb.org",
    "license": "LGPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-26761-Win-Conda_vc14.x-x86_64.7z",
            "hash": "57f698b22caa786a82c6f56d87411f79bf33172f03df564789852b2836a8feed"
        }
    },
    "extract_dir": "FreeCAD_weekly-builds-26761-Win-Conda_vc14.x-x86_64",
    "bin": "bin\\FreeCADCmd.exe",
    "shortcuts": [
        [
            "bin\\FreeCAD.exe",
            "FreeCAD"
        ]
    ],
    "checkver": {
        "url": "https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds",
        "regex": "FreeCAD_weekly-builds-([\\d]+)-Win-Conda"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-$version-Win-Conda_vc14.x-x86_64.7z"
            }
        },
        "hash": {
            "url": "$url-SHA256.txt",
            "regex": "(?sm):\\s+([a-fA-F\\d\\s]+)CertUtil"
        },
        "extract_dir": "FreeCAD_weekly-builds-$version-Win-Conda_vc14.x-x86_64"
    }
}
```

**Comment by rashil2000** [comment]
/verify

I have updated the manifest as per @tech189's comment

**Comment by rashil2000** [comment]
Thanks again @tech189 :)

**Comment by rashil2000** [comment]
The website also calls them weekly:

image

**Comment by tech189** [comment]
Yes, thank you, I forgot to mention that they renamed the pre-releases to weekly.

**Comment by tech189** [comment]
And thank you @pandaero for making this PR, sorry we didn’t get to it earlier!

**Pull request merged**
