### PR TITLE
nheko@nightly: allow 1- or 2-digit regex to fix autoupdate failure

### LINKED ISSUE #642: Nheko regex is causing autoupdate failure
## Bug Report

**Package Name:** Nheko

### Current Behaviour

When autoupdate is running (such as with `./bin/checkver.ps1 *`), nheko autoupdate script includes a `break` command if a matching regex is not found while checking for updates. An incorrectly formatted regex (or a change to the website which causes the regex to no longer match) causes the update script to fail. 

Because the script includes a `break` in case of regex failure (see below), this stops the remainder of app updates from running when `checkver.ps1` is run on all apps

```
  "script": [
      "$url = 'https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/'",
      "$regex = '(?sm)download/neko\\.dev/([A-Za-z]+).*?nheko-master-([0-9a-f]+)-win64\\.zip.*?(\\d{1} [A-Za-z]{3} \\d{4})'",
      "",
      "$cont = (Invoke-WebRequest $url).Content",
      "$matches = [regex]::Matches($cont, $regex)",
      "if (!$matches) { error \"Could not match regex in $url\"; break }",
      "$match = $matches[$matches.Count-1]",
      "",
      "$date = (Get-Date $match.Groups[3].Value).ToString('yyyyMMdd')",
      "$commitSha = $match.Groups[2].Value.SubString(0,6)",
      "$fileUrl = $match.Groups[1].Value",
      "Write-Output $date-$commitSha $fileUrl"
  ],
```

### Expected Behaviour

Nheko update script should use correct regex to find a download URL

### Possible Solution

Modify regex as follows:
```
  "script": [
      "$url = 'https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/'",
      "$regex = '(?sm)download/neko\\.dev/([A-Za-z]+).*?nheko-master-([0-9a-f]+)-win64\\.zip.*?(\\d{1,2} [A-Za-z]{3} \\d{4})'",
      "",
      "$cont = (Invoke-WebRequest $url).Content",
      "$matches = [regex]::Matches($cont, $regex)",
      "if (!$matches) { error \"Could not match regex in $url\"; break }",
      "$match = $matches[$matches.Count-1]",
      "",
      "$date = (Get-Date $match.Groups[3].Value).ToString('yyyyMMdd')",
      "$commitSha = $match.Groups[2].Value.SubString(0,6)",
      "$fileUrl = $match.Groups[1].Value",
      "Write-Output $date-$commitSha $fileUrl"
  ],
```
Notice the change from `d{1}` to `d{1,2}` to accommodate single-digit dates

### System details

**Windows version:** 10

**OS architecture:** 64-bit

**PowerShell version:** 7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-09-12T14:03:57.2096605-04:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

### PR DESCRIPTION
**Pull request by josephst**
Previously, autoupdate failed for nheko (and nheko failure caused failure of all other auto-updates) due to regex not matching. This PR allows for single-digit dates in regex so that matching is successful. 

Closes #642 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by josephst** [comment]
Updated Nheko with new download URLs and bumped package version (old nightly versions no longer available for download).

For what it's worth, it may be better to just remove this package from the Versions repository. The nightly version has to be downloaded from Matrix (rather than being hosted on ie Github Releases or similar). Since it's hosted on Matrix, downloading it requires downloading via Matrix bridge. I was not the original creator of this package, just trying to fix its build problems since the script failing is preventing all other packages from auto-updating.

**Comment by josephst** [comment]
Should be ready for merge. Package updated to latest version. 

Previously, regex would over-match and sometimes offer the Flatpak download URL in place of the Windows .zip download URL

With Regex `(?sm)download/neko\.dev/([A-Za-z]+).*?nheko-master-([0-9a-f]+)-win64\.zip.*?(\d{1,2} [A-Za-z]{3} \d{4})`

image


Now, regex modified to only match a download URL that does NOT have an additional download URL within the match (ie to match the URL closest to the package name and date. 

With Regex `(?sm)download/neko\.dev/([A-Za-z]+)((?!download/neko\.dev/).)*?nheko-master-([0-9a-f]+)-win64\.zip.*?(\d{1,2} [A-Za-z]{3} \d{4})`

image

**Comment by igaryhe** [comment]
@issaclin32 @niheaven @rasa @rashil2000 
sorry for the ping, but this is kind of a severe bug and affecting a bunch of packages. it would be really helpful if this pr could be reviewed and merged as soon as possible.

**Pull request merged**
