### PR TITLE
Adds Blender LTS version 2.83.13

### PR DESCRIPTION
**Pull request by vncastanheira**
Adds option for downloading the LTS version of Blender.

https://www.blender.org/download/lts/

### CODE REVIEW

**Comment by niheaven** [comment]
Don't merge `master` to `master`

**Comment by vncastanheira** [comment]
> 
> 
> Don't merge `master` to `master`

How should I do that?

**Comment by issaclin32** [comment]
> > Don't merge `master` to `master`
> 
> How should I do that?

Merging `userxxx:master` to `ScoopInstaller:master` is fine when you add new files **for the first time**, but this will cause very messy commit history in your future PRs.

You can choose "creating a new branch" when you edit the file.

**Comment by rashil2000** [comment]
Please create new PR as per @issaclin32's suggestion. This one is impossible to review.

**Pull request closed without merging**
