### PR TITLE
openscad-dev: fixed extract_dir bug

### LINKED ISSUE #1131: [Bug]: json bucket manifest typo for openscad-dev
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

openscad-dev

### Expected/Current Behaviour

openscad-dev package fails to install after extraction. Appears to be a typo in the extract_dir property

### Steps to Reproduce

```console
PS> scoop install openscad-dev
Installing 'openscad-dev' (2023.03) [64bit] from versions bucket
OpenSCAD-2023.03.02-x86-64.zip (50.5 MB) [====================================================================] 100%
Checking hash of OpenSCAD-2023.03.02-x86-64.zip ... ok.
Extracting OpenSCAD-2023.03.02-x86-64.zip ... Could not find 'openscad-2023.03.02'! (error 16)
At C:\Users\xxxxx\scoop\apps\scoop\current\lib\core.ps1:638 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...02'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'openscad-2023.03.02'! (error 16)
```

### Possible Solution

Change "extract_dir": "openscad-2023.03.02" to "extract_dir": "openscad-2023.03.02-x86-64" and "extract_dir": "openscad-2023.03.02-x86-32"

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
4ee5dbd3a (HEAD -> master, origin/master, origin/HEAD) todolist: Update to version 8

'main' bucket:
4baed96de (HEAD -> master, origin/master, origin/HEAD) usql: Update to version 0.14.0

'versions' bucket:
b4ec36b22 (HEAD -> master, origin/master, origin/HEAD) prismlauncher-qt5-git: Update to version 7.0-bc1a7d2
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-04-02T15:20:06.0146494+02:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSversionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.832
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.832
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by noygal**
Fixed a bug described on issue: https://github.com/ScoopInstaller/Versions/issues/1131.

Added arch suffix for `extract_dir`.

Closes #1131

- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by noygal** [comment]
Hi @ScoopInstaller/maintainers,

This PR has been open for quite a long time now, can someone review/merge it? I've been testing this on my laptop for the past few versions and it worked fine.

And thanks for all the hard work you're doing, I love the scoop ecosystem and I use it on all my windows machines 🚀

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
