### PR TITLE
Added scribus-devel (ver. 1.5.7)

### PR DESCRIPTION
**Pull request by asakura42**
Closes https://github.com/ScoopInstaller/Extras/issues/7496

### CODE REVIEW

**Comment by rashil2000** [comment]
scribus-devel.json -> scribus-dev.json

**Comment by asakura42** [comment]
@rashil2000 Done. They call their unstable version 'devel' by the way

**Comment by rashil2000** [comment]
/verify

Okay, please mention that in the description - "Open Desktop Publishing (Development Release)"

**Comment by asakura42** [comment]
@rashil2000 Done.

**Pull request merged**
