### PR TITLE
tomcat9: Update to version 9.0.54

### PR DESCRIPTION
**Pull request by thorstenkampe**
Update Tomcat 9 from version 9.0.45 to 9.0.54

### CODE REVIEW

**Review by rashil2000 — DISMISSED** [review]

**Comment by HUMORCE** [comment]
@thorstenkampe please replace all `www.apache.org` with `archive.apache.org`.

**Comment by thorstenkampe** [comment]
@HUMORCE I've updated tomcat9.json with the change you requested on my fork (https://github.com/thorstenkampe/Versions). Is there something else I have to do?

**Review by HUMORCE — APPROVED** [review]

**Comment by HUMORCE** [comment]
everything ok.

thanks

**Pull request merged**
