### PR TITLE
mingw-winlibs(-llvm)-ucrt-mcf: add version 13.2.0-16.0.6-11.0.0-r1

### LINKED ISSUE #1311: [Request]: add MCF Thread Model build of mingw-winlibs
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

mingw-winlibs(-llvm)-ucrt-mcf

### Description

Same as mingw-winlibs(-llvm)-ucrt but built with MCF Threading model instead.

### Homepage

https://winlibs.com

### Download Link(s)

https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.0-ucrt-r1/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.7z  
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.0-ucrt-r1/winlibs-i686-mcf-dwarf-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.7z

https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.0-ucrt-r1/winlibs-x86_64-mcf-seh-gcc-13.2.0-mingw-w64ucrt-11.0.0-r1.7z  
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.0-ucrt-r1/winlibs-i686-posix-dwarf-gcc-13.2.0-mingw-w64ucrt-11.0.0-r1.7z

### Corresponding package

mingw-winlibs

### Some Indication of Popularity/Repute

_No response_

### PR DESCRIPTION
**Pull request by shanoaice**
This PR adds the MCF thread model build of `mingw-winlibs`. The msvcrt version is currently not added because the MSVCRT MCF thread model build does not contain LLVM components and the version name on the website cannot match autoupdate regex.

It also adjusts the autoupdate expression of POSIX thread model build so that it only matches the POSIX build updates.

Closes #1311.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Here, Please discard changes for other manifests, just adding mcf related. Update `checkver` and `autoupdate` according to https://github.com/ScoopInstaller/Versions/commit/87e97bcebccda2c5fc9817ca1ebac1c25381a044

**Comment by shanoaice** [comment]
> Here, Please discard changes for other manifests, just adding mcf related. Update `checkver` and `autoupdate` according to [87e97bc](https://github.com/ScoopInstaller/Versions/commit/87e97bcebccda2c5fc9817ca1ebac1c25381a044)

Reverted all other edits and changed autoupdate according to `87e97bc`.

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
