### PR TITLE
scala2: add version 2.13.7

### PR DESCRIPTION
**Pull request by tech189**
- Relates to #366, especially my intention here:
>Ah yes, I was suggesting scala2.json because I was thinking of updating the Main bucket manifest to v3 since that is the latest available.
>If we did that, you could submit this PR for 2.12.x (i.e. one that does not update to 2.13.x and 2.14.x if that ever releases) and then I could make another one for 2.x that will continue updating.

- Once this is merged, then I can submit a PR to the Main bucket to update scala to v3. I will leave a note for those who upgrade that they can use versions/scala2 if they haven't migrated to v3 yet.
- Manifest entirely copied from the Main bucket, will never update to v3.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Don't know why github actions bot says it doesn't work, works for me and has worked for a while: https://github.com/ScoopInstaller/Main/commits/master/bucket/scala.json
```
scala2: 2.13.7 (scoop version is 2.13.7)
Forcing autoupdate!
Autoupdating scala2
DEBUG[1641347338] [$updatedProperties] = [url extract_dir hash] -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:446:5
DEBUG[1641347338] $substitutions (hashtable) -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:184:5
DEBUG[1641347338] $substitutions.$dotVersion                    2.13.7
DEBUG[1641347338] $substitutions.$basenameNoExt                 scala-2.13.7
DEBUG[1641347338] $substitutions.$patchVersion                  7
DEBUG[1641347338] $substitutions.$matchHead                     2.13.7
DEBUG[1641347338] $substitutions.$majorVersion                  2
DEBUG[1641347338] $substitutions.$preReleaseVersion             2.13.7
DEBUG[1641347338] $substitutions.$matchTail
DEBUG[1641347338] $substitutions.$buildVersion
DEBUG[1641347338] $substitutions.$url                           https://downloads.typesafe.com/scala/2.13.7/scala-2.13.7.zip
DEBUG[1641347338] $substitutions.$version                       2.13.7
DEBUG[1641347338] $substitutions.$basename                      scala-2.13.7.zip
DEBUG[1641347338] $substitutions.$baseurl                       https://downloads.typesafe.com/scala/2.13.7
DEBUG[1641347338] $substitutions.$urlNoExt                      https://downloads.typesafe.com/scala/2.13.7/scala-2.13.7
DEBUG[1641347338] $substitutions.$dashVersion                   2-13-7
DEBUG[1641347338] $substitutions.$minorVersion                  13
DEBUG[1641347338] $substitutions.$match1                        2.13.7
DEBUG[1641347338] $substitutions.$underscoreVersion             2_13_7
DEBUG[1641347338] $substitutions.$cleanVersion                  2137
DEBUG[1641347338] $hashfile_url = $null -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:187:5
Downloading scala-2.13.7.zip to compute hashes!
scala-2.13.7.zip (22.7 MB) [=================================================================================================================] 100%
Computed hash: a52cd39d0c13748b36a389b87ffbf5c4b6bc098af9ea745cf3c874867fd91976
Writing updated scala2 manifest
```

**Comment by issaclin32** [comment]
> Don't know why github actions bot says it doesn't work, works for me and has worked for a while: https://github.com/ScoopInstaller/Main/commits/master/bucket/scala.json

The file name is wrong. You named your file as `scala`, without the `.json` file extension.

**Comment by tech189** [comment]
Oops sorry!

**Review by niheaven — APPROVED** [review]

**Pull request merged**
