### PR TITLE
v2rayn-pre: Update to version 6.25 and Add architectures

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
@HUMORCE plz review
v2rayn-pre: `fix` autoupdate zip package and `Update` to Version 6.24

**Comment by HUMORCE** [comment]
Use `architecture` as well.

https://github.com/2dust/v2rayN/wiki/Release-files-introduction

**Comment by b4imetu** [comment]
/verify
@HUMORCE

**Comment by b4imetu** [comment]
/verify
@HUMORCE architecture added

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
