### PR TITLE
systeminformer-nightly: Add version 3.0.5527

### PR DESCRIPTION
**Pull request by sitiom**
Process Hacker has been renamed to System Informer

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by Jimimaku** [comment]
> Process Hacker wurde in System Informer umbenannt
> 
> * [x] Ich habe den[Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) gelesen.

**Comment by Jimimaku** [comment]
> Alle Änderungen sehen gut aus.
> 
> Warten Sie auf die Überprüfung durch menschliche Mitarbeiter.
> 
> ### systeminformer-nightly
> * [x] Beschreibung
> * [x] Lizenz
> * [x]  Hashes
> * [x] Schachbrett
> * [x] Automatische Aktualisierung

**Comment by rasa** [comment]
Forgife me if I'm misunderstanding, but this appears to be the most current release, and not a beta, alpha, nightly, or older release. As such, wouldn't this belong in the Extras bucket, instead of the Versions bucket?

**Comment by sitiom** [comment]
It is a [nightly build](https://systeminformer.sourceforge.io/nightly.php). System Informer does not have a stable release yet.

**Pull request merged**
