### PR TITLE
php56, php70: Remove autoupdate and fix URL

### PR DESCRIPTION
**Pull request by rasa**
Addresses https://github.com/ScoopInstaller/Versions/issues/21#issuecomment-500088862

### CODE REVIEW

**Comment by niheaven** [comment]
Move to `archives` means php.net has frozen this version (5.6 and 7.0), so please refer to [php55](https://github.com/ScoopInstaller/Versions/blob/master/bucket/php55.json) that remove `autuupdate` and `checkver` and lock its version number to 5.6.40 (for 7.0, to 7.0.33).

Yes, `php70` is broken, too... So why not fix it here?

**Comment by indrakaw** [comment]
Fixing PHP 7.0 is fine too.

**Comment by rasa** [comment]
Seems I can’t approve this myself. @niheaven ?

**Comment by niheaven** [comment]
Wow, but why I can...

It seems one cannot approve oneselves PR.

**Pull request merged**
