### PR TITLE
postgresql: add version 12.09

### PR DESCRIPTION
**Pull request by CaselIT**
This is as https://github.com/ScoopInstaller/Versions/pull/327 but for version 12

### CODE REVIEW

**Comment by CaselIT** [comment]
just checking if there is any update in the pipeline check that caused error in #327 so that this can be merged?

thanks!

**Comment by rashil2000** [comment]
/verify

Let's give it a try

**Comment by CaselIT** [comment]
Thanks for taking a look @rashil2000

**Pull request merged**
