### PR TITLE
inkscape-dev: Fix `.com` bins, and `checkver`

### PR DESCRIPTION
**Pull request by brian6932**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
(tests will fail cause the manifest fully replaces urls, this can be amended)

**Comment by brian6932** [comment]
Can someone please merge?

**Review by niheaven — APPROVED** [review]

**Pull request merged**
