### PR TITLE
kicad-nightly: Add version 27242.0a5438ec88

### PR DESCRIPTION
**Pull request by Duckle29**
Moved here as discussed in: https://github.com/lukesampson/scoop-extras/pull/4740

I decided to remove the 32bit variant, as the versions between 32 and 64 bit can be different, and as such can't use a single checkver

### CODE REVIEW

**Comment by rashil2000** [comment]
@Duckle29 can you update this to the latest version?

**Comment by Duckle29** [comment]
@rashil2000 Sure. I've been running this for a while in my own bucket https://github.com/Duckle29/duckles_bucket/blob/main/bucket/kicad-nightly-x86_64.json Updated it here too

**Comment by rashil2000** [comment]
Rename manifest to kicad-nightly.json.

Add 32bit version too - https://kicad-downloads.s3.cern.ch/windows/nightly/kicad-msvc.r25890.b85fb9137f-i686.exe

**Comment by issaclin32** [comment]
I updated the manifest because the author has not responded for a while.

I seems that *KiCad* still provide 32-bit binaries for [stable releases](https://downloads.kicad.org/kicad/windows/explore/stable), but not for nightly releases.

The is no link for 32-bit version in the [API page](https://kicad-downloads.s3.cern.ch/?prefix=windows/nightly). Also `https://kicad-downloads.s3.cern.ch/windows/nightly/kicad-nightly-r27242.0a5438ec88-i686.exe` is not valid.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
