### PR TITLE
olive-editor-nightly: Add manifest

### PR DESCRIPTION
**Pull request by rashil2000**
~Supercedes https://github.com/ScoopInstaller/Nightlies/pull/5~

/cc @tech189 @igitur

### CODE REVIEW

**Comment by tech189** [comment]
Weird, if I remove the `?<commit>` from the checkver, it can find the first match but when it is present in the regex it fails with
```
olive-editor-nightly: couldn't find new version in https://olivevideoeditor.org/nightly.php
```

**Comment by niheaven** [comment]
The download link is broken, not the checkver

**Comment by rashil2000** [comment]
There's no standalone download link - for the latest commit the link is autogenerated - https://pipelines.actions.githubusercontent.com/1c6iFqqsb2xjqxpqTiRaXKF4ohKFYNxrjGM4jJDoWBQjKxRBX3/_apis/pipelines/1/runs/1014/signedartifactscontent?artifactName=Olive-2a80b858-Windows-x86_64.zip&urlExpires=2021-12-09T12%3A45%3A31.1495930Z&urlSigningMethod=HMACV2&urlSignature=OZAFoD5bhTumOlCfk%2Fdyj9ZiBFckzPqxfpeuys5Glrk%3D

**Comment by tech189** [comment]
Ah that's annoying. It would be good if scoop had a feature like homebrew which could follow links to their destination like here: https://github.com/Homebrew/homebrew-cask/blob/cca22db6636ffa378621ff9c610c7bb32a7c44d2/Casks/geogebra.rb#L12

Although that wouldn't fix the fact that the autogenerated page is behind another page with a 5 second wait.

**Comment by igitur** [comment]
`oliver-nightly` ;-)

**Comment by igitur** [comment]
@rashil2000 Do I have write access to this branch/PR? If so, I'll try to fix the manifest.

**Comment by rashil2000** [comment]
I don't know how to give access, I don't see any option. Would you prefer opening a new PR from your end? I'll close this then.

**Comment by niheaven** [comment]
Paste working manifest in comment, and we could edit the PR.

**Comment by igitur** [comment]
> There's no standalone download link - for the latest commit the link is autogenerated - https://pipelines.actions.githubusercontent.com/1c6iFqqsb2xjqxpqTiRaXKF4ohKFYNxrjGM4jJDoWBQjKxRBX3/_apis/pipelines/1/runs/1014/signedartifactscontent?artifactName=Olive-2a80b858-Windows-x86_64.zip&urlExpires=2021-12-09T12%3A45%3A31.1495930Z&urlSigningMethod=HMACV2&urlSignature=OZAFoD5bhTumOlCfk%2Fdyj9ZiBFckzPqxfpeuys5Glrk%3D

Oh, I see what you mean by this. I thought it would be an easy fix, but apprently not.

**Comment by rashil2000** [comment]
Closing as there's no solution as of now...

**Pull request closed without merging**
