### PR TITLE
DBeaver Nightly: Add version 24.3.0-2024-11-20

### PR DESCRIPTION
**Pull request by igitur**
Add new manifest for DBeaver Early Access. https://dbeaver.io/files/ea/

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by igitur** [comment]
All checks are passing. Please review this.

**Comment by igitur** [comment]
Please @HUMORCE 🙏🏻

**Comment by igitur** [comment]
Sorry, manifest was already a day old. Updated again now.

**Comment by HUMORCE** [comment]
Only the version needs to be captured.

**Comment by igitur** [comment]
The `24.3.0` part doesn't change until the next release. Only the date part changes with the daily version. If I remove the date part, I'll lose out on the daily versions, which is the goal of this package.

**Comment by HUMORCE** [comment]
Renamed to `dbeaver-ea`

**Comment by igitur** [comment]
Thanks!

**Comment by uJZk** [comment]
Have an extra "," at the end

```
> scoop search dbeaver
ConvertFrom-Json : 传入的数组无效，结尾多出了“,”。 (840): {
    "version": "24.3.0-2024-11-20",
    "description": "Database tool for developers, SQL programmers, database administrators and analys
ts. (Early Access)",
    "homepage": "https://dbeaver.io",
    "license": "Apache-2.0",
    "suggest": {
        "java": [
            "java/oraclejdk",
            "java/oraclejre8",
            "java/openjdk11"
        ]
    },
    "architecture": {
        "64bit": {
            "url": "https://dbeaver.io/files/ea/dbeaver-ce-24.3.0-win32.win32.x86_64.zip",
            "hash": "a164dd477e070b3e0e50aa062fdcd32b46aba74025eed265ec6a5a618ed1724f"
        }
    },
    "extract_dir": "dbeaver",
    "bin": [
        [
            "dbeaver.exe",
            "dbeaver-cli.exe"
        ],
        [
            "dbeaver-ea.exe",
            "dbeaver-cli.exe"
        ],
    ],
    "shortcuts": [
        [
            "dbeaver.exe",
            "DBeaver EA"
        ]
    ],
    "checkver": {
        "url": "https://dbeaver.io/files/ea/",
        "regex": "href=\"dbeaver-ce-(?<ver>[\\d.]+)-win32.win32.x86_64.zip\".*</td><td>(?<date>\\d{4}
-\\d{2}-\\d{2}) \\d{2}:\\d{2}:\\d{2}</td>",
        "replace": "${ver}-${date}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://dbeaver.io/files/ea/dbeaver-ce-$matchVer-win32.win32.x86_64.zip"
            }
        }
    }
}
所在位置 C:\Users\123\scoop\apps\scoop\current\libexec\scoop-search.ps1:101 字符: 66
+ ... e]::ReadAllText($_.FullName) | ConvertFrom-Json -ErrorAction Continue
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJson
   Command

Results from local buckets...

Name       Version              Source   Binaries
----       -------              ------   --------
dbeaver    24.2.5               extras
dbeaver-ea 2024.3-243.21565.212 versions
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Versions/commit/ff7b7be5eb4ae5c3184f575191ec7d5011e5d2b9

**Pull request merged**
