### PR TITLE
php-7.*: Fix url path

### PR DESCRIPTION
**Pull request by ismoil-nosr**
Changes:
- Fix url path for PHP 7.2 & PHP 7.3 versions
- Remove checkver
- Remove autoupdate

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Have they stopped updating the 7.2 and 7.3 versions?

**Comment by ismoil-nosr** [comment]
> Have they stopped updating the 7.2 and 7.3 versions?

Seems like that, [yes](https://www.php.net/supported-versions.php)

**Comment by rashil2000** [comment]
Could you please add a description to each manifest?

**Pull request merged**
