### PR TITLE
sumatrapdf-pre: Add Version 15234

### PR DESCRIPTION
**Pull request by b4imetu**
Closes https://github.com/ScoopInstaller/Extras/pull/9043

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
I think we should check whether it's okay to add the package first, the website says "Please do not redistribute" - I've opened a discussion [here](https://github.com/sumatrapdfreader/sumatrapdf/discussions/2895) on their GitHub.

Also if it's okay, I think we should name it `sumatrapdf-pre` just like `obs-studio-pre`, `espanso-pre`

**Comment by GitHubRulesOK** [comment]
Just note the time while a bad pre-release is available can sometimes be extended the last 3 weeks have shown this test version as causing crashes easily for 2 different reasons both now rectified in 15252 but for those versions **especially this one** its been a support nightmare not needing  any enhancing of automated circulation SumatraPDFs inbuilt update notice does it too well as it is

**Comment by b4imetu** [comment]
@GitHubRulesOK 
For the stable version of `sumatrapdf`, it is already provided in another bucket called `Extras`.
See https://github.com/ScoopInstaller/Extras/blob/master/bucket/sumatrapdf.json
The current version is 3.4.6.

In this `Versions` bucket, I want to provide the unstable pre-release version, named `sumatrapdf-pre`, hoping to give users who need to use the latest version an option.

I think there is no need to worry about the stability of the pre-release. The users of the pre-release version must have the habit of frequent updates.

And with `checkver`, `autoupdate` and `github-actions`, the manifest will automatically synchronize with the official website updates

**Pull request closed without merging**
