### PR TITLE
Add vlc-nightly

### LINKED ISSUE #284: [Request] Add VLC Nightly
- **URL to application**: https://nightlies.videolan.org/
- **Latest version**: nightly
- **Graphical interface**: Yes
- **Portable version**: Yes

### PR DESCRIPTION
**Pull request by tech189**
- Closes #284
- Based on https://github.com/ScoopInstaller/Extras/blob/master/bucket/vlc.json
- Using a similar technique to checkver in https://github.com/ScoopInstaller/Extras/pull/7586
- ~Caveat: extract_dir will need to be updated once the nightly moves from 4.0 to 4.1/5.0 etc.~ Fixed in second commit

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Looks like the same issue with github actions as with the inkscape PR, checks pass but do not complete successfully for some reason. https://github.com/ScoopInstaller/Versions/runs/4623107957?check_suite_focus=true
```
INFO: Checkver

Log of Output:

    GET with 0-byte payload 
    received 39196-byte response of content type text/html 
    GET with 0-byte payload 
    received 1409-byte response of content type text/html 
    GET with 0-byte payload 
    received 39771-byte response of content type text/html 
    GET with 0-byte payload 
    received 1409-byte response of content type text/html 
    vlc-nightly:  
    20211223 
     (scoop version is 20211223) 
     
    Forcing autoupdate! 
    Autoupdating vlc-nightly 
    Searching hash for  
    vlc-4.0.0-dev-win32-4716c6f7.7z 
     in  
    artifacts.videolan.org/vlc/nightly-win32/20211223-0420/SHA512SUM 
    Found:  
    sha512:3c727a602adff1fbe077519b8a2b20d816d8309b217c149051a5ec84ad6d2256c3454758c244239b88d98683e6e1259cdf178046f4e19627141b5aea3a68098d 
     using  
    Extract Mode 
    Searching hash for  
    vlc-4.0.0-dev-win64-4716c6f7.7z 
     in  
    artifacts.videolan.org/vlc/nightly-win64/20211223-0422/SHA512SUM 
    Found:  
    sha512:72fcba361cc3eaec994e1c66d1f85dd5b2bba52c09c5b62eb0e745ded03007b4b1003411180828049e5d72e9fb4b227cf0a00b69c2ba9a423bc3b783c85b1f25 
     using  
    Extract Mode 
    Writing updated vlc-nightly manifest

INFO: Checkver done
```

**Comment by rashil2000** [comment]
Can we somehow suppress the `GET` part? Try putting `6>$null` at the end of Invoke-WebRequest.

**Comment by LazyGeniusMan** [comment]
> Can we somehow suppress the `GET` part? Try putting `6>$null` at the end of Invoke-WebRequest.

or try to fix the github action bot? instead of using `($outputV[1] -like "$($object.version)")` to verify, maybe it should've search an array index that match `$object.version` ?, something like `($outputV -Contains "$($object.version)")`. I could try to fix it but I dont even know how to test it locally.

**Comment by rashil2000** [comment]
You can run these two lines locally (in bucket folder):

```powershell
$outputV = @(.\bin\checkver.ps1 -App vlc-nightly -Force *>&1)

$checkver = ((($outputV.Count -ge 2) -and ($outputV[1] -like "20211223")))
```

**Comment by LazyGeniusMan** [comment]
> And see whether $checkver is true or false

It's false, I think it's because github action bot have a little bit different log output. In client machine, the log ouput would be a one line of `vlc-nightly: 20211224 (scoop version is 20211224)`, but github action log output would be:
```
vlc-nightly: 
20211224
 (scoop version is 20211224)
```
it has multiple line, which is why the current verification is `$OutputV[1]`, because it's try to match it with the 2nd line of the output

**Comment by LazyGeniusMan** [comment]
> And see whether $checkver is true or false

this code output is `true` :
```
$outputV = @(~\scoop\apps\scoop\current\bin\checkver.ps1 -App vlc-nightly -Dir "~/scoop-test" -Force *>&1)
$checkver = ((($outputV.Count -ge 2) -and ($outputV -match "20211224")))
Write-Host $checkver
```
Should I make a PR to https://github.com/ScoopInstaller/Scoop-GithubActions/blob/main/src/Action/PR.psm1#L191 ?

**Comment by rashil2000** [comment]
Yes

**Comment by LazyGeniusMan** [comment]
@issaclin32 Isn't this PR supposed to be merged? probably mistaken this as an issue?

**Comment by tech189** [comment]
I hope it was a mistake 😅 Let's see if the checks are fixed

/verify

**Comment by LazyGeniusMan** [comment]
@tech189 run `checkver.ps1` locally for this manifest and commit the new version, your inkspace PR is passed

**Comment by tech189** [comment]
Oh no looks like Appveyor checks are broken because the github pages http://scoop.sh/draft/schema#/definitions/license is down! 😥

**Comment by issaclin32** [comment]
> @issaclin32 Isn't this PR supposed to be merged? probably mistaken this as an issue?

It was triggered by this line **fix ScoopInstaller/Versions#356** and ScoopInstaller/Extras#7586, so merging  ScoopInstaller/Scoop-GithubActions#2 accidentally closed this. 🤣

**Pull request merged**
