### PR TITLE
syncplay-beta: Update to version 1.7.1-RC1

### PR DESCRIPTION
**Pull request by brian6932**
Fixes `checkver.script` and `autoupdate.url`
The repo's inconsistent with using `v` in tags, so a case was added for stripping it
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
Can someone merge this please?

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
