### PR TITLE
(nodejs)nodejs20: Add version 20.8.1 (new LTS)

### PR DESCRIPTION
**Pull request by jdpowell1**
Adds support for nodejs20 (which will be LTS very shortly)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Roemer** [comment]
It is LTS now, so this can probably be merged now.

**Comment by Roemer** [comment]
Any reason this is not merged yet?

**Comment by HUMORCE** [comment]
#1421

**Pull request closed without merging**
