### PR TITLE
Add scala 2.12.13

### PR DESCRIPTION
**Pull request by adambridge**
Add scala 2.12.13

### CODE REVIEW

**Comment by tech189** [comment]
@adambridge could you update the manifest to 2.13.0 and rename the manifest to `scala2.json` so it has a stable name?

**Comment by adambridge** [comment]
Salve @tech189! From what I see with other packages my feeling is that scala212 would be the right name for scala 2.12.x which is what I wanted when I added this (the main bucket had 2.13.x)

I should be able to fix the checkver regex/url tomorrow, I copied it from the main bucket but it isn't right there either. I think it should be
"url": "https://www.scala-lang.org/download/all.html",
"regex": "Scala 2\\.12\\.([\\d.]+)"

**Comment by tech189** [comment]
Salve @adambridge! Sunt qui linguam Latinam intellegant in Scoop?! Mirabile visu! :)

Ah yes, I was suggesting `scala2.json` because I was thinking of updating the Main bucket manifest to v3 since that is the latest available.

If we did that, you could submit this PR for 2.12.x (i.e. one that does not update to 2.13.x and 2.14.x if that ever releases) and then I could make another one for 2.x that will continue updating.

Also could you make a PR from a branch other than the base branch like `adambridge-scala`?

**Comment by adambridge** [comment]
@tech189, 'intellegant' might be a stretch but I do recognise it!

I've made a new PR from a non-base branch adambridge-scala as suggested: https://github.com/ScoopInstaller/Versions/pull/366

**Comment by tech189** [comment]
Hahahae, it's good to see! If you want to see some more Latin/programming cross-over check out my Roman date program, [Ab Urbe Condita](https://github.com/tech189/Ab-Urbe-Condita/)!

Perfect, going to test and review it now.

**Pull request closed without merging**
