### PR TITLE
(ipfilter,ffmpeg)-nightly: Add try/catch to `checkver.script`

### PR DESCRIPTION
**Pull request by brian6932**
Minor: stricter `checkver.regex`

Reason: When `checkver.script` fails due to gh rate limits, it falls back to the default `checkver`

[Example](https://github.com/ScoopInstaller/Versions/commit/d23b52ae7488f563a9307df84b4c84ef77271c1e)
[Example 2](https://github.com/ScoopInstaller/Versions/commit/42cab9c3fa46de8ecf6f16c5383f760662aa84fa)
[Example 3](https://github.com/ScoopInstaller/Versions/commit/0a8f4aea3dd97b563085550df40fb9615b8c0684)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by brian6932** [comment]
@rasa Please merge this when you get the chance 👍

**Comment by brian6932** [comment]
Actions' checkver failing when rate limited is intended, as that is preferred over getting the wrong version info

**Pull request merged**
