### PR TITLE
chromium-dev: Update to version 99.0.4806.0-r955034 and fix autoupdate

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Closes #XXXX

Relates to https://github.com/ScoopInstaller/Extras/issues/7292

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

## Notes
- List of files can be found here: https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697721304?check_suite_focus=true#step:3:10
- Should I also add bin & scripts that's used in ungoogled-chromium ?

### CODE REVIEW

**Comment by rashil2000** [comment]
> Should I also add bin & scripts that's used in ungoogled-chromium ?

Yes

**Comment by rashil2000** [comment]
checkver failing

**Comment by LazyGeniusMan** [comment]
hmm wierd, it was working before: https://github.com/LazyGeniusMan/Sc00p-Test/commit/39b79860d01d9f243f759dc9dd41c3933bc3a682#diff-f80e869bfe31ae8cc38226fee713a99d39c5daaa15ae734ff426d8bda9b0d664

wait let me run excavator again

**Pull request merged**
