### PR TITLE
kicad-nightly-lite: Add version r20311.50e22de3ba

### PR DESCRIPTION
**Pull request by diggit**
This is addition to https://github.com/lukesampson/scoop-extras/pull/5529, but nightly version this time.
Probably already outdated version (I don't have windows machine nearby at this moment). I rely on auto updates by Excavator.

### CODE REVIEW

**Comment by diggit** [comment]
Now I see that. i686 and x86_64 builds have different version because commits happen quite often and thet occur even between builds.
https://kicad-downloads.s3.cern.ch/index.html?prefix=windows/nightly/

Any suggestion?

The only solution I got is separate manifest fo 32bit and 64bit variants....

**Comment by rashil2000** [comment]
Can you update this to the latest version?

> i686 and x86_64 builds have different version because commits happen quite often and they occur even between builds.

That's fine. We can keep same version for both, and the manifest will only update itself when both 32 and 64bit builds are at same versions.

**Comment by diggit** [comment]
Issue is no longer present. I'll update manifest next week.

**Comment by tech189** [comment]
Here's an updated manifest - there are no longer 32bit binaries available: https://downloads.kicad.org/kicad/windows/explore/nightlies
```
{
    "version": "r27499.f14dc9e305",
    "description": "Electronics Design Automation Suite, nightly build without libraries",
    "homepage": "https://kicad.org",
    "license": "GPL-3.0-only",
    "architecture": {
        "64bit": {
            "url": "https://kicad-downloads.s3.cern.ch/windows/nightly/kicad-nightly-r27499.f14dc9e305-x86_64-lite.exe#/dl.7z",
            "hash": "6ec3214d982c3a61259ce65a71a3846f74ca2e885ea722d8d0211f2aa9db0e3d"
        }
    },
    "pre_install": "Remove-Item \"$dir\\`$*\", \"$dir\\Uninst*\" -Recurse",
    "bin": [
        [
            "bin\\kicad.exe",
            "kicad-nightly"
        ]
    ],
    "shortcuts": [
        [
            "bin\\kicad.exe",
            "KiCad-nightly"
        ]
    ],
    "notes": "You should configure environment paths KICAD6_3DMODEL_DIR, KICAD6_FOOTPRINT_DIR, KICAD6_SYMBOL_DIR, KICAD6_TEMPLATE_DIR, KICAD_USER_TEMPLATE_DIR, otherwise they'll default to $dir\\share\\kicad",
    "checkver": {
        "url": "https://kicad-downloads.s3.cern.ch/?delimiter=/&prefix=windows/nightly/",
        "regex": "<Key>windows/nightly/kicad-nightly-(r\\d+\\.[a-z0-9]+)-x86_64-lite\\.exe</Key>",
        "reverse": true
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://kicad-downloads.s3.cern.ch/windows/nightly/kicad-nightly-$version-x86_64-lite.exe#/dl.7z"
            }
        }
    }
}

```

**Comment by tech189** [comment]
For some reason the file was last updated today according to this page: https://downloads.kicad.org/kicad/windows/explore/nightlies
Should checkver look at the `<LastModified>` tag too?

**Comment by rashil2000** [comment]
Sure. 

Let's handle this in a new PR.

**Comment by rashil2000** [comment]
Superceded by #512

**Pull request closed without merging**
