### PR TITLE
prusaslicer-pre: Add version 2.5.0-rc2

### PR DESCRIPTION
**Pull request by b4imetu**
`prusaslicer-pre` includes alpha/beta/rc releases in [PrusaSlicer GitHub releases page](https://github.com/prusa3d/PrusaSlicer/releases)

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
Sorry I should have raised a request issue. But now I need help with `checkver`  and  `autoupdate`

**Comment by tech189** [comment]
I removed 32bit as the last 32bit version was released in April. Checkver should be fixed now.

**Review by tech189 — APPROVED** [review]

**Comment by b4imetu** [comment]
[PrusaSlicer 2.5.0](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.5.0) is out now.

And version management of `prusaslicer-pre` is a bit difficult because the package naming has changed (ends with _signed.zip)

**Review by tech189 — CHANGES_REQUESTED** [review]
I don't think this package in the Versions bucket should update to the stable version - can you adapt the regex so that it picks up only `PrusaSlicer-x.x.x-(alpha/beta/rc)+win64`?

**Comment by b4imetu** [comment]
> I don't think this package in the Versions bucket should update to the stable version - can you adapt the regex so that it picks up only `PrusaSlicer-x.x.x-(alpha/beta/rc)+win64`?

I just want to update this Manifest in sync with GitHub; if that doesn't work, I could revert to the previous commit. #f81376f

> And version management of `prusaslicer-pre` is a bit tricky because the package naming has changed (ends with _signed.zip)
> I also don't know how the next GitHub release will be named *

My ability to modify the regex is pretty limited. V.V

**Comment by tech189** [comment]
Most of the other packages in this bucket usually stick to the latest unstable version only, rather than whichever version is the latest (stable or unstable). You can install both packages and then use `scoop reset <package>` to set the shortcut and shims to the version you wish to use.

> My ability to modify the regex is pretty limited. V.V

I'll take a look soon

**Comment by tech189** [comment]
> My ability to modify the regex is pretty limited. V.V

A regex that matches the latest unstable version: `PrusaSlicer-([\d.]+)-(\w+)\+win64-(?<timestamp64>\d+)(?:_signed)?.zip`

If releases in the future contain _signed then this regex should also match them!

Could you add this and revert back to 2.5.0-rc2?

**Comment by b4imetu** [comment]
> A regex that matches the latest unstable version: `PrusaSlicer-([\d.]+)-(\w+)\+win64-(?<timestamp64>\d+)(?:_signed)?.zip`
> If releases in the future contain _signed then this regex should also match them!

Thank you^^

> Could you add this and revert back to 2.5.0-rc2?

I revert back to `2.5.0-rc2` but I'm not sure about changing of the `autoupdate` url's `_signed`

**Comment by tech189** [comment]
> Thank you^^

No problem!

> I revert back to 2.5.0-rc2 but I'm not sure about changing of the autoupdate url's _signed

Leave `_signed` out of the autoupdate for now so that the checks can pass and I'll add it back if they do in fact use it for the next build.

**Comment by b4imetu** [comment]
https://github.com/ScoopInstaller/Versions/pull/630/commits/3a6ceeede668a1d10307ae9038b3845f41186511 do not pass the check while https://github.com/ScoopInstaller/Versions/pull/630/commits/f81376ff5f229b4955d0b0d55f0a22e922e4b839 passed the check, Maybe the new regex didn't work

**Comment by b4imetu** [comment]
@issaclin32

**Pull request merged**
