### PR TITLE
ffmpeg-gyan-nightly: Add version 2021-12-23

### LINKED ISSUE #350: [Request] Add ffmpeg-gyan-nightly
- **URL to application**: <https://www.gyan.dev/ffmpeg/builds/>
- **Latest version**:2021-12-12-git-996b13fac4
- **Graphical interface**: No
- **Portable version**: Yes

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Closes #350 

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Let me know if I should only use the date for the version

### CODE REVIEW

**Comment by rashil2000** [comment]
> Let me know if I should only use the date for the version

How many releases are made each day? If there's only one, we can omit the commit tag

**Comment by LazyGeniusMan** [comment]
> > Let me know if I should only use the date for the version
> 
> How many releases are made each day? If there's only one, we can omit the commit tag

Looks like it will release a build per 3 days

**Comment by rashil2000** [comment]
Great, thanks!

**Pull request merged**
