### PR TITLE
Add CosmosDB Explorer

### PR DESCRIPTION
**Pull request by aloneguid**
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
- 64bit app
- checkver is incorrect

**Comment by aloneguid** [comment]
So what do we do now?

**Comment by aloneguid** [comment]
Forget it, not worth the effort.

**Comment by rashil2000** [comment]
- You need to use architecture 64bit block
- You need to use a custom regex for checkver because of the 'beta' string

**Comment by aloneguid** [comment]
I'm not going to do that, are you crazy?

**Comment by rashil2000** [comment]
Why even bother opening a PR if you can't respond to feedback? Do you like wasting other people's time? Is this the first time you've ever opened a PR?

**Comment by aloneguid** [comment]
I've raised the PR twice, and your comments were far from helpful. Myself and others are **working for free** to add to the catalog and you can't even bother to help. If this process is awkward and manual from stone ages, than maybe you need to change your attitude and actually help, because at the moment it does feel like you are in a way for no reason.

**Comment by rashil2000** [comment]
If you had actually read the simple contributing guide, there would've been no problems at all. Yours isn't the first PR I've encountered here. Hundreds of first-time contributors are doing just fine, seems like only you have problems.

Oh, and what part of the process is awkward and manual? If you can't bother to at least read up a tiny bit about the manifests (as I said, the guide is more than enough) before making any contributions (here or anywhere else for that matter), kindly refrain from contributing.

**Comment by aloneguid** [comment]
Dude that's actually not true, check before you write something. I've contributed to Scoop and have packages live. Where there were errors others were able to point out in the PR. The problem is YOU having an attitude like the world owns you something. Please kindly leave the team, the world will be a better place.

**Comment by aloneguid** [comment]
@lukesampson can we please do something about this "helpful" person?

**Comment by rashil2000** [comment]
@tech189 would you like to take this up?

**Pull request closed without merging**
