### PR TITLE
Add python 3.8 manifest

### PR DESCRIPTION
**Pull request by thesebas**

### CODE REVIEW

**Comment by JanPokorny** [comment]
@rasa Please merge this, just today I ran into a package that required Python 3.8 specifically...

**Comment by thesebas** [comment]
@Yoglib, you've closed #229 because this one already exists, but why you've closed this one?

**Comment by JanPokorny** [comment]
@niheaven @r15ch13 @rasa Sorry to bother, but I would really love this one merged. It's a trivial change over the python37 manifest, as you can imagine. I am aware that we can install the manifest manually in the meantime, but that's a bit messy to maintain.

**Comment by JanPokorny** [comment]
@r15ch13 Thank you! You might as well merge #225 to be clear once 3.10 comes out

**Pull request merged**
