### PR TITLE
duplicati-canary: Add version 2.0.6.104_canary_2022-06-15

### PR DESCRIPTION
**Pull request by Zliced13**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
It's not in an offical bucket. See https://scoop.sh/#/apps?q=duplicati&s=0&d=1&o=false

**Comment by rasa** [comment]
It's also being added to Extras at https://github.com/ScoopInstaller/Extras/pull/9533

**Comment by Zliced13** [comment]
> It's also being added to Extras at https://github.com/ScoopInstaller/Extras/pull/9533

I know, but this is the canary version of the app which has new experimental features in it, unlike the latest version of it.

**Review by rasa — APPROVED** [review]

**Pull request merged**
