### PR TITLE
fluxctl: Move from 'Main' bucket

### PR DESCRIPTION
**Pull request by niheaven**
Relates to https://github.com/ScoopInstaller/Versions/pull/401#issuecomment-1019313849

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
It is deprecated, but still receives updates. Latest is 1.24.3 - https://github.com/fluxcd/flux/releases

**Comment by niheaven** [comment]
It's strange that someone delete this one's `checkver`, and I just move the manifest... Add it again.

**Comment by rashil2000** [comment]
It was removed by Ash258 🙃

They've done it many times in the past, no idea why

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
> It was removed by Ash258 🙃
> 
> They've done it many times in the past, no idea why

It's a temporary solution when the author stops or temporally stops providing windows binary, in most cases 😄

**Pull request merged**
