### PR TITLE
tachidesk-server-preview: Add version 0.6.5-r1136

### PR DESCRIPTION
**Pull request by Frostedfox**
preview version of tachidesk-server

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
https://github.com/ScoopInstaller/Versions/actions/runs/3064426596/jobs/5257003124 reports
```
RuntimeException: The following 1 lines contain trailing whitespace: 
[24](https://github.com/ScoopInstaller/Versions/actions/runs/3064426596/jobs/5257003124#step:4:25)
      File: D:\a\Versions\Versions\my_bucket\bucket\tachidesk-server-preview.json, Line: 46
[25](https://github.com/ScoopInstaller/Versions/actions/runs/3064426596/jobs/5257003124#step:4:26)
      at <ScriptBlock>, D:\a\Versions\Versions\scoop_core\test\Import-File-Tests.ps1: line 109
[26](https://github.com/ScoopInstaller/Versions/actions/runs/3064426596/jobs/5257003124#step:4:27)
    [+] any leading whitespace consists only of spaces (excepting makefiles) 74ms
[27](https://github.com/ScoopInstaller/Versions/actions/runs/3064426596/jobs/5257003124#step:4:28)

**Comment by rasa** [comment]
And personally, I would like to see us not [download ancillary scripts](https://github.com/ScoopInstaller/Versions/pull/649/files#diff-4915feaa03d0ecfba469001db6404c1cf8dc54ae21c69b88c3eef2454ab2764fR13), but to use [$bucketdir](https://github.com/ScoopInstaller/Versions/search?q=%24bucketsdir). Primarily because you don't need to change URLs after testing it locally.

**Comment by tech189** [comment]
I fixed the checks failing and changed it to use `$bucketsdir` instead. Should we include the release build number (`-r1136`) in the version number so that it can be picked up as a new version when running `scoop update`?

**Comment by niheaven** [comment]
Of course, the version should be 0.6.5-r1136, not only 0.6.5.

**Review by tech189 — APPROVED** [review]

**Comment by Jimimaku** [comment]
> preview version of tachidesk-server
> 
> * [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

**Comment by Jimimaku** [comment]
> preview version of tachidesk-server
> 
> * [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

**Pull request merged**
