### PR TITLE
nodejs22: Add version 22.11.0

### LINKED ISSUE #1994: [Request]: nodejs22
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

nodejs22

### Description

An asynchronous event driven JavaScript runtime designed to build scalable network applications.

### Homepage

https://nodejs.org/

### Download Link(s)

https://nodejs.org/dist/latest-v22.x/node-v22.10.0-win-x64.7z

### Corresponding package

nodejs22

### Some Indication of Popularity/Repute

107k stars, 29.4k forks, that's Node.js :)

### PR DESCRIPTION
**Pull request by val1984**
Closes #1994

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by val1984** [comment]
Hello @HUMORCE and sorry for pinging,
We are currently in the zone when Node.js 20 is still LTS but Node.js 23 is current, resulting in not being able to install Node.js 22 with scoop currently.
Thank you in advance for having read me.

**Review by HUMORCE — APPROVED** [review]

**Comment by val1984** [comment]
Thank you for reviewing 👍

**Comment by HUMORCE** [comment]
`main/nodejs-lts` has been updated to v22.11.0

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
