### PR TITLE
Latest Tomcat 9 version from the extras bucket

### PR DESCRIPTION
**Pull request by thorstenkampe**
Includes persistence patch from conf and webapps directories

### CODE REVIEW

**Comment by thorstenkampe** [comment]
Relates to https://github.com/ScoopInstaller/Versions/issues/283

**Comment by thorstenkampe** [comment]
URLs are incorrect - 9.0.45 is available from https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.45/bin/. Not sure if I can update my pull request...

**Comment by janicmikes** [comment]
There is already a PR for tomcat9 which includes the persistence patch for the previous versions as well
#280

**Comment by HUMORCE** [comment]
duplicate https://github.com/ScoopInstaller/Versions/pull/280

**Pull request closed without merging**
