### PR TITLE
lua51: make shims consistent

### LINKED ISSUE #540: lua51: Inconsistent shims
## Bug Report

**Package Name:** Lua 5.1

### Current Behaviour

While installing this package shims `lua5.1` and `luac5.1` will be added (among others), which is inconsistent with other `lua` packages.

### Expected Behaviour

It should add shims `lua51` and `luac51` instead to be consistent.

### PR DESCRIPTION
**Pull request by EtiamNullam**
Closes #540 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Have you tested the manifest by installing it?

**Comment by EtiamNullam** [comment]
Sorry, I assumed inside `[]` at `bin` its a list of shims for for binary above, so I thought it will be just an easy fix by comparing to other releases. It doesn't work. Apparently executable at version `5.1` really has that extra dot.

I would test it before if I knew its so easy.

**Comment by EtiamNullam** [comment]
I fixed my error.

I was not sure about removing direct shims but I did it in 9bc2ff4, its a newly added package and a bit niche so for sure nobody depends on it yet. I couldn't find similar scenario in other manifests, but I see its common to not include ugly binary names in favor to those human-readable.

**Comment by rashil2000** [comment]
The convention is to include the supplied binary name, and create additional human-readable shims. So don't remove them, just add new ones.

**Comment by EtiamNullam** [comment]
What about other packages that don't comply?

Examples:
```
[
  "bin\\BeefIDE.exe",
  "beefn"
],
[
  "bin\\BeefBuild.exe",
  "BeefBuildN"
],
[
  "dockerd.exe",
  "docker.exe"
]
```

In most terminal emulators triggering completion (`<Tab>`) from `lua5` will expand to `lua5.1` first before `lua51`, so later user might assume it will be the same for other packages and might try to run `lua5.3` after installing package `lua53` which will fail.

**Comment by issaclin32** [comment]
@rashil2000 This looks fine to me, should we merge this PR?

**Comment by EtiamNullam** [comment]
Current situation with `lua` packages:

- `Lua 5.4`: install by `scoop install lua`, run by `lua54`, binary `lua54.exe`
- `Lua 5.3`: install by `scoop install lua53`, run by `lua53`, binary `lua53.exe`
- `Lua 5.1`: install by `scoop install lua51`, run by `lua5.1`, binary `lua5.1.exe`

Of course any can be also ran by simple `lua` if `scoop reset` is applied to it.

If we make Lua 5.1 shims compliant with new versions we can forget about the fact that its different.

> Perhaps someone else who uses Lua more regularly can chime in.

@rashil2000: I won't count on it, as I was the one to suggest adding `Lua 5.1` package (issue #537) just recently.

**Pull request merged**
