### PR TITLE
zig-dev: Add version 0.9.0-dev.1678

### PR DESCRIPTION
**Pull request by thomastay**
Adds a version for the master branch of Ziglang.
This is basically the same as #185, but made even simpler without the regex that now doesn't work.
I'm not sure why that PR was abandoned, but I think this would be a worthwhile addition. Please let me know if you want me to make any changes.

I have tested it and this works very well in automatically updating zig for me.

### CODE REVIEW

**Comment by issaclin32** [comment]
Please name the package as `zig-master` rather than `ziglang-master`.
(the stable version in *Extras* is now named `zig`)

Also, I think naming the package as `-dev` would be clearer than `-master`. Do you agree?

**Comment by niheaven** [comment]
Does build metadata here make sense? Ref: https://semver.org/#spec-item-10

If dev version and build metadata change simultaneously, the metadata should be removed from version number.

**Comment by issaclin32** [comment]
> If dev version and build metadata are changed simultaneously, the metadata should be removed from version number.

I agree. There is no reason to keep "build metadata".
By the way, I think the file name should be **zig**-dev.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
