### PR TITLE
systeminformer-nightly: Fix `architecture.extract_dir`, and fixed other small errors

### PR DESCRIPTION
**Pull request by Zliced13**
Fixes this bug that I had with this app while updating it.
(WindowsTerminal)14l2p6_12-28-2022

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by leumasme** [comment]
I wonder why this manifest now manually moves files to&from the persist dir instead of using the regular scoop persist?

Also, unstalling System Informer should restore the default Task Manager if it was changed to System Informer via the System Informer Options. The regular uninstaller does this, the scoop uninstall does not.
The Task Manager Replacing is accomplished via a String Registry key called `Debug` located at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe` set to the path of the System Informer exe.
If this is not removed but the System Informer exe was removed, trying to start taskmanager in any way will fail ("taskmgr.exe not found").
Additionally, System Informer installed via scoop seems to create this registry key with the exact version path instead of `\current\` so I suspect it would break when updating?

**Comment by Zliced13** [comment]
> I wonder why this manifest now manually moves files to&from the persist dir instead of using the regular scoop persist?

Because persisting a file that already exists inside the folder will mess up future installations of the program via Scoop.

**Comment by leumasme** [comment]
Ah, I see what you mean. The persisted files exist in the downloaded zip from the start. See https://github.com/winsiderss/systeminformer/issues/1585 - apparently this is how they detect that SystemInformer is running in portable mode

**Pull request merged**
