### PR TITLE
konversation-nightly: Update to version 1048

### LINKED ISSUE #1772: [Bug]: konversation | download not found | project download source changed | new CI | 403
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

konversation

### Expected/Current Behaviour

firefox_SWiZrO17NP

Download source changed:
Binary factory has been replaced by gitlab.
https://blogs.kde.org/2024/01/30/farewell-binary-factory-add-craft-jobs-your-apps-kdes-gitlab-now/

The CI builds for Windows are labeled with `craft_windows` now.

Build jobs moved here:
https://invent.kde.org/network/konversation/-/jobs

Articafts page:
https://invent.kde.org/network/konversation/-/artifacts

Latest artifact build job at the from:
https://invent.kde.org/network/konversation/-/jobs/1867805

Artifact.zip download link:
https://invent.kde.org/network/konversation/-/jobs/1867805/artifacts/download?file_type=archive

Sctructure:

1.

image

2.

image

3. Executable:

image

### Steps to Reproduce

```console
1. scoop install versions/konversation
2. see issue
```

### Possible Solution

Lead 1:
Binary factory has been replaced by gitlab.
https://blogs.kde.org/2024/01/30/farewell-binary-factory-add-craft-jobs-your-apps-kdes-gitlab-now/

### Scoop and Buckets Version

```console
Current Scoop version:
d337bb1f (HEAD -> master, tag: v0.4.2, origin/master, origin/HEAD) chore(release): Bump to version 0.4.2 (#5964)

'main' bucket:
da6185d09 (HEAD -> master, origin/master, origin/HEAD) shadowsocks-rust: Update to version 1.19.2

'extras' bucket:
74721d5bd (HEAD -> master, origin/master, origin/HEAD) upscayl: Update to version 2.11.5

'versions' bucket:
7962a2188 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.13.0-dev.349

'nerd-fonts' bucket:
a6b9261c (HEAD -> master, origin/master, origin/HEAD) SarasaGothic: Update to version 1.0.13

'nonportable' bucket:
fe9ee988 (HEAD -> master, origin/master, origin/HEAD) k-lite-codec-pack-standard-np: Update to version 18.3.5

'games' bucket:
5b3d0c0df (HEAD -> master, origin/master, origin/HEAD) xenia-canary: Update to version 20240601130505-ce990e2
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
01/06/2024 13:35:30 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by aliesbelik**
- Migrate from binary-factory.kde.org.
- Update to the latest version.

Closes #1772
Relates to #1662

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Wonder if this should/could be renamed into `konversation-nightly` (although manifest for stable version still not present in known buckets).

**Comment by niheaven** [comment]
Please do the renaming

**Comment by Spacellary** [comment]
Thanks for the PR for issue 1772, looks like this was the last KDE application needing to be migrated, from what I could see.

**Pull request merged**
