### PR TITLE
fix olive-editor-nightly (fixes #660)

### LINKED ISSUE #660: `olive-editor-nightly` does not install
## Bug Report

**Package Name:** `olive-editor-nightly`

### Current Behaviour

Installing through `scoop install olive-editor-nightly` does not work. The following error is presented:

```
PS G:\projects\personal\scoop-versions-bucket> scoop install olive-editor-nightly
Installing 'olive-editor-nightly' (7fea1476) [64bit] from versions bucket
The remote server returned an error: (404) Not Found.
URL https://nightly.link/olive-editor/olive/workflows/ci/master/Olive-7fea1476-Windows-x86_64.zip.zip is not valid
```

### Expected Behaviour

Package should install correctly and be ready to use after running `scoop install olive-editor-nightly`.

### Possible Solution

I've fixed it on https://github.com/ScoopInstaller/Versions/compare/master...rmobis:scoop-versions-bucket:master, just by updating the `url`, setting the `extract_dir` property and removing the workaround for it being a `.zip.zip` file previously. I have a PR drafted and ready to be submitted as soon as you allow it.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 5.1.22000.832

**Additional software:** Windows Terminal

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-09-21T21:03:35.8919215-03:00"
}
```

### PR DESCRIPTION
**Pull request by rmobis**
This fixes `olive-editor-nightly` install by updating the download URL following the new standards on their repo. Also removes the workaround for extracting the `.zip.zip` file, as that's no longer needed.

Closes #660

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by KrisSchneider** [comment]
@rmobis do you mind typing `/verify`. It seems me and @rasa are unable to do so for your manifest.

**Review by tech189 — APPROVED** [review]
Tested installation and autoupdate.

**Comment by tech189** [comment]
Oh sorry, I forgot to change the commit name, should be `olive-editor-nightly: Fix checkver and installation (fixes #660)`

**Pull request merged**
