### PR TITLE
cuda: Add version 11.7 11.8

### LINKED ISSUE #1092: [Request]: cuda11.8
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] English interface (or at least English documentation)
- [X] Alternative, forked or prerelease version of an existing package
- [X] Fairly standard install (e.g. no elaborate pre/post install scripts)

### Name

cuda11.8

### Description

cuda11.8

### Homepage

https://developer.nvidia.com/cuda-toolkit

### Download Link(s)

https://developer.nvidia.com/cuda-toolkit

### Corresponding package

versions

### Some Indication of Popularity/Repute

_No response_

### PR DESCRIPTION
**Pull request by jinfar**
Closes #1092 #1043

Relates to #1092 #1043

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by efonte** [comment]
The URL of CUDA 11.8 is wrong:

original:
`http://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows#/dl.7z`

fixed:
`http://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows.exe#/dl.7z`

**Comment by jinfar** [comment]
You are right, thank you.

**Comment by jinfar** [comment]
I have made another pr https://github.com/ScoopInstaller/Versions/pull/1159

**Pull request closed without merging**
