### PR TITLE
aws1: Add version 1.18.144

### PR DESCRIPTION
**Pull request by dennisroche**
See https://github.com/ScoopInstaller/Main/pull/1395

Updated `aws` in main bucket to `2.x` and **migrated** `1.x` to `aws1` [versions](https://github.com/ScoopInstaller/Versions) bucket

### CODE REVIEW

**Comment by xfournet** [comment]
Shouldn't be updated to 1.18.139 ? This is the current latest tag of aws-cli 1.x, see https://github.com/aws/aws-cli/releases/tag/1.18.139
I don't why the aws is stuck to v1.18.44 in main repo, it seem the autoupdate system doesn't work anymore on aws. I put a notice here https://github.com/ScoopInstaller/Main/pull/835#issuecomment-642926655 but no one take care of it...

**Comment by dennisroche** [comment]
it probably should be 1.18.139. i have just migrated it as-is from the main bucket as I saw that the last update was rolled back for some reason.

**Comment by xfournet** [comment]
It seems it was a problem of decompression on a specific release (https://github.com/ScoopInstaller/Main/issues/1021) you could test with the latest version, if the problem is gone ?

**Comment by dennisroche** [comment]
> It seems it was a problem of decompression on a specific release ([ScoopInstaller/Main#1021](https://github.com/ScoopInstaller/Main/issues/1021)) you could test with the latest version, if the problem is gone ?

Updated to (1.18.144)[https://github.com/aws/aws-cli/blob/master/CHANGELOG.rst]

**Comment by dennisroche** [comment]
Any value getting this merged? I don't think so.

**Pull request closed without merging**
