### PR TITLE
aria2-134: Add last version with SSLv3.0 and TLSv1.0 support.

### PR DESCRIPTION
**Pull request by MaxPeal**
aria2-1.34 LAST version with SSLv3.0 and TLSv1.0 support

### CODE REVIEW

**Comment by MaxPeal** [comment]
Checkver must fail as is it Not the Last Version of aria2, but the last with SSLv3.0 and TLSv1.0 support

**Comment by issaclin32** [comment]
> Checkver must fail as is it Not the Last Version of aria2, but the last with SSLv3.0 and TLSv1.0 support

I don't think `checkver` and `autoupdate` is needed for this package. We can just remove it.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
