### PR TITLE
everything-beta: Add version 1.4.1.1002

### PR DESCRIPTION
**Pull request by TheRandomLabs**
I know that at the moment, it's the same as the version in `extras`, but this will change when there's a new beta out.

### CODE REVIEW

**Review by tech189 — CHANGES_REQUESTED** [review]
Works great for me, could you please run checkver to update the version number and hashes to the latest beta?

**Comment by rashil2000** [comment]
`"persist"` is missing, is it intenttional?

**Comment by tech189** [comment]
I think it fails because a new release is available.

**Pull request merged**
