### PR TITLE
pdfbox3: Add version 3.0.0-alpha2

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Review by tech189 — CHANGES_REQUESTED** [review]
I would make a few changes such as adding autoupdate and cleaning up unnecessary `[]` around `url` and `hash`. 

Here's my edited manifest:
```json
{
    "version": "3.0.0-alpha2",
    "description": "Java tool for working with PDF documents.",
    "homepage": "https://pdfbox.apache.org",
    "license": "Apache-2.0",
    "suggest": {
        "JDK": "java/openjdk"
    },
    "url": "https://dlcdn.apache.org/pdfbox/3.0.0-alpha2/pdfbox-3.0.0-alpha2.jar#/pdfbox3.jar",
    "hash": "sha512:c2a338bb1312ad3bbcc72b557121cd7fbd64966f970735ad8c706051a3b2b065284a3b86792cb7dd0afd2e4e6ff7be39aca4056b54a6314359ea1533396cbed5",
    "bin": "pdfbox3.jar",
    "checkver": {
        "url": "https://pdfbox.apache.org/download.html",
        "regex": "Alpha release for PDFBox 3\\.0\\.0 &mdash; <a href=\"https:\\/\\/www\\.apache\\.org\\/dist\\/pdfbox\\/([\\d.]+-alpha[\\d]+)\\/"
    },
    "autoupdate": {
        "url": "https://dlcdn.apache.org/pdfbox/$version/pdfbox-$version.jar#/pdfbox3.jar",
        "hash": {
            "url": "$url.sha512",
            "regex": "$sha512"
        }
    }
}
```

One thing that needs discussing is whether to add this program as `pdfbox3` or `pdfbox-beta` or `pdfbox-dev` or something else. Usually apps with a version number in the name are old such as `python27`.

**Comment by tech189** [comment]
Seems okay apart from the appveyor failure, but we have been having issues with it recently so it might be nothing (it says something about needing a final line with whitespace). Let's wait for the maintainers to check.

**Comment by sualeh** [comment]
@tech189 - ready to merge now, I think.

**Comment by tech189** [comment]
> One thing that needs discussing is whether to add this program as `pdfbox3` or `pdfbox-beta` or `pdfbox-dev` or something else. Usually apps with a version number in the name are old such as `python27`.

Not quite, maintainers should discuss this - I think they might not want the number in the manifest name as including the version number signifies a stable old release, not one that might change in the future to 4 or 5 etc.

**Comment by rashil2000** [comment]
`pdfbox-alpha` would be a better name

**Comment by niheaven** [comment]
Use this and rename manifest to `pdfbox-alpha`

```json
{
    "version": "3.0.0-alpha2",
    "description": "Java tool for working with PDF documents.",
    "homepage": "https://pdfbox.apache.org",
    "license": "Apache-2.0",
    "suggest": {
        "JDK": "java/openjdk"
    },
    "url": [
        "https://downloads.apache.org/pdfbox/3.0.0-alpha2/pdfbox-app-3.0.0-alpha2.jar#/pdfbox.jar",
        "https://downloads.apache.org/pdfbox/3.0.0-alpha2/preflight-3.0.0-alpha2.jar#/preflight.jar"
    ],
    "hash": [
        "sha512:3e9a9f26eb0c55d80adf63d13bdf0962ee08c0e958e6cb268cfe42df92fc7045ad33c6f73aec73e24087593d14826d5670079fc119246b554ef79d728740d7d6",
        "sha512:c25f8d22ff8e9555a6d7f9573b79759fe00af243e17a49c5c4f2f2a3583e16d90ead19defa1226408083ae707a342f579937a25e879e55ec4210aa223e875a12"
    ],
    "bin": [
        "pdfbox.jar",
        "preflight.jar"
    ],
    "checkver": {
        "url": "https://pdfbox.apache.org/download.html",
        "regex": "Alpha release.*?>([\\w.-]+)<"
    },
    "autoupdate": {
        "url": [
            "https://downloads.apache.org/pdfbox/$version/pdfbox-app-$version.jar#/pdfbox.jar",
            "https://downloads.apache.org/pdfbox/$version/preflight-$version.jar#/preflight.jar"
        ],
        "hash": {
            "url": "$url.sha512"
        }
    }
}
```

**Pull request merged**
