### PR TITLE
godot-mono-beta: Add version 4.0-beta4

### PR DESCRIPTION
**Pull request by tsilenzio**
Relates to #748

* [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by niheaven** [comment]
Why is this called `godot-mono-beta`? What's the `mono` mean?

**Comment by tsilenzio** [comment]
> Why is this called `godot-mono-beta`? What's the `mono` mean?

Godot has two versions per release: standard and mono. The mono version officially adds support for C#/.NET, whereas regular doesn't and only supports GDScript (Godot's own programming language that's similar to but different than Python).

**Comment by tsilenzio** [comment]
No need to apologize. Yeah that's correct. Specifically it requires .NET 6.0 (the current .NET LTS release) but since Microsoft acquired the comp0any that made Mono .NET & Mono are now one and the same.

If interested you can read more here (liked version is for the 4.0 beta release where stable is for 3.4)
https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_basics.html

To use C# it states:
> In summary, you must have installed the .NET SDK and the Mono-enabled version of Godot.

**Pull request merged**
