### PR TITLE
Add .github folder

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
Can someone please review? I can’t approve/merge it myself. Thx

**Review by chawyehsu — APPROVED** [review]

**Comment by Ash258** [comment]
You will have lots of duplicated commits and merges of branches, since there are 2 excavator running now.

**Comment by rasa** [comment]
> You will have lots of duplicated commits and merges of branches, since there are 2 excavator running now.

Understood. But isn't that the case for main and extras, as well?

**Comment by Ash258** [comment]
No. They do not have any scheduled running jobs

**Comment by chawyehsu** [comment]
@rasa The actions did fail very well.. https://github.com/ScoopInstaller/Versions/actions?query=workflow%3AExcavator

**Pull request merged**
