### PR TITLE
taiga-beta: Make `persist` explicit

### PR DESCRIPTION
**Pull request by brian6932**
The reason for this is because inside the `data` dir, `db\anime-relations.txt` (https://github.com/erengy/anime-relations) and `theme` can receive updates relatively often, and `theme` is not very user customizable.

Relates to https://github.com/ScoopInstaller/Extras/pull/11833

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
Any mergers?
The PR in the other repo was merged, but this one was just ignored

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
