### PR TITLE
Steam Mover: Added version 0.1 (closes #4048)

### PR DESCRIPTION
**Pull request by Vedabahu**
This PR adds the application Steam Mover. Information about it is discussed in ScoopInstaller/Extras#4048. 

> It is is just a GUI for moving a folder and leaving a symbolic link/junction behind. Also use this tool to move non-Steam games such as standalone games.

More information can be found [here](https://www.traynier.com/software/steammover).
It has been tested on Windows Vista, 7, 8, 8.1. Windows 10 & 11 - not tested.

> It requires NTFS formatted drives. It will not work with FAT32.

This can also be just used to free up space in your drives.

It is no longer in production and was last `committed on Nov 4, 2014`. It is _frozen_.
Hence I am adding this to Versions repo.
I have not added `checkver` and `autoupdate` as I am pretty sure there will be no new versions released.

Closes ScoopInstaller/Extras#4048

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
?

**Comment by Vedabahu** [comment]
> ?

You asked me to rename it. So I did that.

**Comment by rashil2000** [comment]
This is what your commit did:

image

**Comment by Vedabahu** [comment]
Oh... sorry. I will fix it tomorrow. My bad.

**Comment by Vedabahu** [comment]
@rashil2000 Done. Can you check it once please.

**Pull request merged**
