### PR TITLE
Add `extract_dir` property on odin and odin-dev

### LINKED ISSUE #1778: [Bug]: odin and odin-dev extraction problem
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

odin, odin-dev

### Expected/Current Behaviour

Scoop could not find `odin.exe` during the shim setting in the installation process.

### Steps to Reproduce

```console
PS> scoop update odin
Updating Scoop...
Updating Buckets...
Scoop was updated successfully!
odin: 2024-05 -> 2024-06
Updating one outdated app:
Updating 'odin' (2024-05 -> 2024-06)
Downloading new version
Loading odin-windows-amd64-dev-2024-06.zip from cache.
Checking hash of odin-windows-amd64-dev-2024-06.zip ... ok.
Uninstalling 'odin' (2024-05)
Unlinking ~\scoop\apps\odin\current
Installing 'odin' (2024-06) [64bit] from 'versions' bucket
Loading odin-windows-amd64-dev-2024-06.zip from cache.
Extracting odin-windows-amd64-dev-2024-06.zip ... done.
Linking ~\scoop\apps\odin\current => ~\scoop\apps\odin\2024-06
Creating shim for 'odin'.
Get-Command: C:\Users\[redacted]\scoop\apps\scoop\current\lib\install.ps1:783
Line |
 783 |              $bin = (Get-Command $target).Source
     |                      ~~~~~~~~~~~~~~~~~~~
     | The term 'odin.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included,
     | verify that the path is correct and try again.
Can't shim 'odin.exe': File doesn't exist.
```

### Possible Solution

From 2024-06 release, The files inside the archive are now located in the `windows_artifacts` directory. It is the same as 'odin-nightly'.

Thus, the solution is really simple. Add `extract_dir` property to each manifest, and set to `windows_artifacts`.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
d337bb1f (HEAD -> master, tag: v0.4.2, origin/master, origin/HEAD) chore(release): Bump to version 0.4.2 (#5964)

'main' bucket:
2c9121843 (HEAD -> master, origin/master, origin/HEAD) red: Update to version 05jun24

'extras' bucket:
de86b88f3 (HEAD -> master, origin/master, origin/HEAD) openvpn-connect@3.2.3.1851: Fix hash (Closes #13402)

'versions' bucket:
5405224af (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20240605
```

### Scoop Config

```console
PS> scoop config

last_update           : 2024-06-05 16:36:25
debug                 : True
aria2-enabled         : True
aria2-warning-enabled : False
use_external_7zip     : True
scoop_branch          : master
scoop_repo            : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by Capella87**
Closes #1778

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by heretique — APPROVED** [review]

**Comment by lost22git** [comment]
```diff
+ "extract_dir": "dist"
```
It is working for me

**Comment by tensor-programming** [comment]
On the normal odin.json, it worked for me to add the change from the above comment.  I didn't see any `windows_artifacts` folder.

**Comment by denovodavid** [comment]
It's been inconsistent for the past few releases due to issues with executable permissions, see https://github.com/odin-lang/Odin/issues/3994

**Comment by thoughton** [comment]
https://github.com/ScoopInstaller/Versions/pull/1779#issuecomment-2267389334 also worked for me to install the latest `odin-dev`.

**Comment by Capella87** [comment]
Yes. this issue is outdated because the problem was solved already in https://github.com/odin-lang/Odin/issues/3994 . Therefore close this issue. Thank you!

**Pull request closed without merging**
